services:
  game-of-life:
    build:
      context: .
    container_name: game-of-life-1
    platform: linux/amd64
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ./.config:/root/.config
      - ./.local:/root/.local
    # Enables interactive TTY so you can attach and use Neovim
    stdin_open: true
    tty: true
